// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAK(arg1, arg2) {
  return window['go']['main']['App']['AddAK'](arg1, arg2);
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function CreateTask(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function ExpandCount(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExpandCount'](arg1, arg2, arg3);
}

export function ExportTaskCSV(arg1, arg2) {
  return window['go']['main']['App']['ExportTaskCSV'](arg1, arg2);
}

export function ExportTaskDialog(arg1) {
  return window['go']['main']['App']['ExportTaskDialog'](arg1);
}

export function ExportTaskGeoJSON(arg1) {
  return window['go']['main']['App']['ExportTaskGeoJSON'](arg1);
}

export function GetAKItems() {
  return window['go']['main']['App']['GetAKItems']();
}

export function GetCities(arg1) {
  return window['go']['main']['App']['GetCities'](arg1);
}

export function GetCounties(arg1, arg2) {
  return window['go']['main']['App']['GetCounties'](arg1, arg2);
}

export function GetExportConfig() {
  return window['go']['main']['App']['GetExportConfig']();
}

export function GetProvinces() {
  return window['go']['main']['App']['GetProvinces']();
}

export function GetTaskLogs(arg1) {
  return window['go']['main']['App']['GetTaskLogs'](arg1);
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PauseTask(arg1) {
  return window['go']['main']['App']['PauseTask'](arg1);
}

export function RemoveAK(arg1) {
  return window['go']['main']['App']['RemoveAK'](arg1);
}

export function ResetAKPool() {
  return window['go']['main']['App']['ResetAKPool']();
}

export function ResumeTask(arg1) {
  return window['go']['main']['App']['ResumeTask'](arg1);
}

export function SetExportConfig(arg1) {
  return window['go']['main']['App']['SetExportConfig'](arg1);
}
