// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {task} from '../models';
import {store} from '../models';

export function AddAK(arg1:string,arg2:string):Promise<string>;

export function CancelTask(arg1:string):Promise<boolean>;

export function CreateTask(arg1:string,arg2:string,arg3:number,arg4:number,arg5:Array<main.TaskTargetInput>,arg6:Array<main.SearchTermInput>):Promise<task.Task>;

export function DeleteTask(arg1:string):Promise<boolean>;

export function ExpandCount(arg1:number,arg2:number,arg3:Array<main.TaskTargetInput>):Promise<number>;

export function ExportTaskCSV(arg1:string,arg2:string):Promise<string>;

export function ExportTaskDialog(arg1:string):Promise<string>;

export function ExportTaskGeoJSON(arg1:string):Promise<string>;

export function GetAKItems():Promise<Array<main.AKInfo>>;

export function GetCities(arg1:string):Promise<Array<string>>;

export function GetCounties(arg1:string,arg2:string):Promise<Array<string>>;

export function GetExportConfig():Promise<store.ExportConfig>;

export function GetProvinces():Promise<Array<string>>;

export function GetTaskLogs(arg1:string):Promise<Array<task.LogEntry>>;

export function GetTaskRecords(arg1:string):Promise<Array<task.Record>>;

export function GetTasks():Promise<Array<task.Task>>;

export function GetVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ImportSearchTerms():Promise<string>;

export function PauseTask(arg1:string):Promise<boolean>;

export function RemoveAK(arg1:string):Promise<string>;

export function ResetAKPool():Promise<void>;

export function ResumeTask(arg1:string):Promise<boolean>;

export function RetryTask(arg1:string):Promise<boolean>;

export function SetExportConfig(arg1:Array<string>):Promise<string>;
